name: App CI

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master/hamburger_client'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build app --file app/Dockerfile --tag app:$(date +%s)
